package main

import (
	"fmt"
	"os"
	"task-5/internal/fib"
)

func main() {
	// Calculate Fibonacci(10) using the internal function.
	value := fib.Fibonacci(10)
	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main

// GeneratedFibonacci is computed as Fibonacci(10) during generation.
const GeneratedFibonacci = %d
`, value)

	// Write generated code to file in the current directory.
	if err := os.WriteFile("generated_fib.go", []byte(content), 0644); err != nil {
		fmt.Println("Error generating file:", err)
		os.Exit(1)
	}
	fmt.Println("generated_fib.go generated successfully.")
}
